language: android

android:
  components:
    # required for running the emulator needed for the instrumented tests
    - android-19
    - sys-img-armeabi-v7a-android-19

install:
  # accept google sdk licenses: required for running `gradle`
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"

before_script:
  # build `signpost` library
  - cd app/libs/signpost
  - mvn package
  - cd ../../..
  # launch the android emulator and wait for it to finish booting
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  